### ISSUE TITLE
cif2cell update issue

### ISSUE THREAD

**Issue by MartijnVandewiele1997** [torbjornbjorkman/cif2cell#20]
Hello everyone

I am a student from professor Stefaan Cottenier. He asked me to provide some data on the operating system I use and the errors involved in this cif2cell problem.

I am using Windows 10 as my primary operating system, with Ubuntu 18.04 as a dual boot. I installed Quantum Mobile 20.06.1 as a VM on the Windows platform. I already updated the cif2cell in aiida:
![image](https://user-images.githubusercontent.com/73488771/97225098-75b06e80-17d2-11eb-92b1-49364424f2e8.png)

In the next screenshot, you see one input file with the name basicVtryout which has the keyword and one without the keyword, called bacicVryoutwithoutkeyword. Cif2cell gives for both cases no error, the only issue is that if I try to run a pw.x on the first file, it works fine, but on the second file without the database_code None, it fails to do the job (not shown on the screenshot here).
![image](https://user-images.githubusercontent.com/73488771/97224873-13576e00-17d2-11eb-8b09-36082dcb8a4b.png)
A look at the *.in files reveals no anomalies there, they look OK.

I attached the .in and .cif files that I used, converted to txt files.
[basicVtryout.in.txt](https://github.com/torbjornbjorkman/cif2cell/files/5441422/basicVtryout.in.txt)
[basicVtryoutwithoutkeyword.in.txt](https://github.com/torbjornbjorkman/cif2cell/files/5441423/basicVtryoutwithoutkeyword.in.txt)
[closedpacked.cif.txt](https://github.com/torbjornbjorkman/cif2cell/files/5441424/closedpacked.cif.txt)
[closedpackedversion2.cif.txt](https://github.com/torbjornbjorkman/cif2cell/files/5441425/closedpackedversion2.cif.txt)

**Comment by ltalirz** [comment]
Closing - it turns out cif2cell does what it is supposed to after all.
See https://github.com/marvel-nccr/quantum-mobile/issues/142#issuecomment-717058752
