### ISSUE TITLE
Python 3.9 compatibility

### ISSUE THREAD

**Issue by merkys** [torbjornbjorkman/cif2cell#21]
I am trying to use `cif2cell` on Python 3.9. First of all, I ran into problem with `fractions` no longer containing `gcd`, thus I have replaced the following line

https://github.com/torbjornbjorkman/cif2cell/blob/3014ade2439237fac56d1b0fbe740c54e832ba3a/cif2cell/uctools.py#L41

with `from math import gcd` (old code of `fractions` recommended that). However, some of the tests still crash with the following trace:

```
Traceback (most recent call last):
  File "binaries/cif2cell", line 490, in <module>
    cd.primitive()
  File "cif2cell/uctools.py", line 288, in primitive
    self.getCrystalStructure(reducecell=True)
  File "cif2cell/uctools.py", line 758, in getCrystalStructure
    divisor = reduce(gcd,L)
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by ltalirz** [comment]
@merkys looking in the [python docs](https://docs.python.org/3/library/fractions.html) it seems that `fractions.gcd` used to return floats in some cases.
Perhaps the error comes because `gcd` is now an int and `L` is a float?

I'm happy to merge PR that fixes this.

**Comment by merkys** [comment]
Thanks for the information regarding `gcd`. I might give this issue a shot.

**Comment by merkys** [comment]
Thanks for a fix!

**Comment by ltalirz** [comment]
just released 2.0.0a3 on pypi as well

**Comment by merkys** [comment]
@ltalirz git tag for 2.0.0a3 is missing.

**Comment by ltalirz** [comment]
thanks, added

**Comment by merkys** [comment]
I still cannot see it at https://github.com/torbjornbjorkman/cif2cell/tags.

**Comment by ltalirz** [comment]
sorry, now I also understand why it was missing before - I pushed the tags to my fork only. fixed!

**Comment by merkys** [comment]
Great, thanks, now I see it!
