### ISSUE TITLE
cannot read H-M long version ?

### ISSUE THREAD

**Issue by stefaan-cottenier** [torbjornbjorkman/cif2cell#27]
When starting from this P1 cif cell :

data_global
_cell_length_a 2.7061
_cell_length_b 4.41901
_cell_length_c 4.6871
_cell_angle_alpha 90
_cell_angle_beta 90
_cell_angle_gamma 90
symmetry_space_group_name_H-M 'P 1'
loop
symmetry_equiv_pos_as_xyz
'x,y,z'
loop
_atom_site_label
_atom_site_type_symbol
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
Fe1 Fe 0.75 0.75 0.916666667
Fe2 Fe 0.25 0.25 0.083333333
Al1 Al 0.25 0.75 0.416666667
Al2 Al 0.75 0.25 0.583333333

and running it subsequently through FINDSYM in order to include symmetry info (https://stokes.byu.edu/iso/findsym.php), this cif is produced :

CIF file created by FINDSYM, version 7.1.3
data_findsym-output
_audit_creation_method FINDSYM

_cell_length_a 2.7061000000
_cell_length_b 4.4190100000
_cell_length_c 4.6871000000
_cell_angle_alpha 90.0000000000
_cell_angle_beta 90.0000000000
_cell_angle_gamma 90.0000000000
_cell_volume 56.0496680665

_symmetry_space_group_name_H-M "P 21/m 21/m 2/n (origin choice 2)"
_symmetry_Int_Tables_number 59
_space_group.reference_setting '059:-P 2ab 2a'
_space_group.transform_Pp_abc a,b,c;0,0,0

loop_
_space_group_symop_id
_space_group_symop_operation_xyz
1 x,y,z
2 x+1/2,-y,-z
3 -x,y+1/2,-z
4 -x+1/2,-y+1/2,z
5 -x,-y,-z
6 -x+1/2,y,z
7 x,-y+1/2,z
8 x+1/2,y+1/2,-z

loop_
_atom_site_label
_atom_site_type_symbol
_atom_site_symmetry_multiplicity
_atom_site_Wyckoff_label
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
_atom_site_occupancy
_atom_site_fract_symmform
Fe1 Fe 2 a 0.25000 0.25000 -0.08333 1.00000 0,0,Dz
Al1 Al 2 b 0.25000 0.75000 0.58333 1.00000 0,0,Dz

#end of cif
[H-M and Hall symbol issue for cif2cell.pdf](https://github.com/torbjornbjorkman/cif2cell/files/7395106/H-M.and.Hall.symbol.issue.for.cif2cell.pdf)

When given the latter as input for cif2cell, there is an error. The attached pdf describes why. Please consider whether or not it is relevant to update cif2cell in order to avoid this problem. The real issue most likely is at the obsolete format used by FINDSYM.

[H-M and Hall symbol issue for cif2cell.pdf](https://github.com/torbjornbjorkman/cif2cell/files/7395106/H-M.and.Hall.symbol.issue.for.cif2cell.pdf)

**Comment by dr-geeno** [comment]
I am not very familiar with H-M notation, but this would require either some kind of conversion function or adding them manually in the table in the spacegroupdata.py file. Otherwise, as you already pointed out in your pdf, one simply need to change the notation on the cif file manually, from long to short.

`_symmetry_space_group_name_H-M "P 21/m 21/m 2/n (origin choice 2)"`

`_symmetry_space_group_name_H-M "P m m n :2"`
