### ISSUE TITLE
conda package outdated

### ISSUE THREAD

**Issue by anish-mudaraddi** [torbjornbjorkman/cif2cell#29]
Hi,

I noticed the Conda package for cif2cell is rather outdated (1.2.10): 
https://anaconda.org/conda-forge/cif2cell

Could you please update it to 2.0.0a3 like the one available via PyPI:
https://pypi.org/project/cif2cell/

Thanks

**Comment by ltalirz** [comment]
Hi guys, the [cif2cell conda-forge feedstock](https://github.com/conda-forge/cif2cell-feedstock) is maintained by @npavlovikj and I'm sure she would appreciate a pull request to update it.

It's quite straightforward - just edit the [meta.yaml](https://github.com/conda-forge/cif2cell-feedstock/blob/main/recipe/meta.yaml) to update the version, the url (switch to [github](https://github.com/torbjornbjorkman/cif2cell/archive/refs/tags/2.0.0a3.tar.gz)) and the sha256 of the the new file (compute with `sha256sum`).

Anyone up for this?

**Comment by anish-mudaraddi** [comment]
Thanks @ltalirz 

Submitted the PR:
https://github.com/conda-forge/cif2cell-feedstock/pull/7#issue-1183213035
