### ISSUE TITLE
Errors on fleur inpgen execution of files generated by cif2cell

### ISSUE THREAD

**Issue by igorjrd** [torbjornbjorkman/cif2cell#40]
Hello,

First of all, I would like to thank all the people involved on development and maintaining of this very useful project. I hope I can cite this on my works soon.

I was trying to generate an input to be evaluated by Fleur input generator (inpgen) using cif2cell. The file generation with cif2cell was executed successfully, but the inpgen throwed an error when I tried to use this to generate the real Fleur input (xml file). It seems like the error is related just by the lack of one slash indicating the end of input instruction line.

I edited the cif2cell code in my machine to fix this and after that the inpgen performed well, so seems to be a quite easy fix. I can even open a PR with this fix if you think that it makes sense.

**Comment by ltalirz** [comment]
Hi @igorjrd cif2cell is currently looking for a maintainer, but please feel welcome to open a pull request if your fix is simple, it will certainly help others who face the same problem

**Comment by igorjrd** [comment]
Hi @ltalirz unfortunately I have being very busy doing a sabbatical in my PhD while I still have some other repositories to maintain. However, I will probably be using cif2cell to prepare my PhD DFT calculation input files, so if I face additional bugs or something like this I will try to do new contributions.
