### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by merkys** [torbjornbjorkman/cif2cell#42]
I noticed that after [2.0.0a5](https://github.com/torbjornbjorkman/cif2cell/releases/tag/2.0.0a5) no more releases were tagged, although `setup.py` contains newer version numbers. Please tag releases in git.

**Comment by dr-geeno** [comment]
I think only @torbjornbjorkman or @ltalirz can do it

**Comment by ltalirz** [comment]
hey @merkys , thanks for the reminder; pushed the 2.1.0 tag

**Comment by merkys** [comment]
Thanks @ltalirz!
