### ISSUE TITLE
castep cif labels tag wrong

### ISSUE THREAD

**Issue by jkshenton** [torbjornbjorkman/cif2cell#43]
Thanks for creating this very useful tool! A particularly useful feature is the exporting of cif labels to e.g. castep cell files. However, I noticed that the tag used for this is wrong: it should be `LABEL` instead of `ID` (Castep crashes with an error saying it doesn't know what `ID` is). 

I think the fix is simply to replace ID with LABEL on this line:

https://github.com/torbjornbjorkman/cif2cell/blob/de4e631f103d6afa7b04e3f0b603f9df3c4d5e74/cif2cell/ESPInterfaces.py#L1612

many thanks!

**Comment by dr-geeno** [comment]
Hey @jkshenton 
thank you for your contribution. I merged your request.
